### ISSUE TITLE
connection closed on leaving "The End"

### ISSUE THREAD

**Issue by Sunekaer** [p455w0rd/p455w0rds-Library#10]
"An existing connection was forcibly closed by the remote host" on leaving "The End" the first time

https://pastebin.com/VvazBAy0

forge-14.23.2.2611
p455w0rdslib-1.12-2.0.28

**Comment by p455w0rd** [comment]
yeah we're doing stuff on the webhost..in the next release of pwlib, I'm relying on GitLab rathr than my webhost..but in the mean time we're trying to figure out a good method of redirection..hang in there

**Comment by p455w0rd** [comment]
should be fixed by #14
