### ISSUE TITLE
Error spam: java.lang.Throwable:printStackTrace:634

### ISSUE THREAD

**Issue by patrickreader** [p455w0rd/p455w0rds-Library#13]
My logs have been spammed with `[TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)` and alternately `TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at p455w0rdslib.util.ContributorUtils$DLThread.run(ContributorUtils.java:316)`. 

Occasionally it prints `Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty` which is an existing issue with my system only.
However, the fact still remains that p455w0rdslib is spamming when there is an error. 
These are spammed about 20 times a second (maybe every tick therefore).
They were spammed so much that my launcher crashed having run out of hard drive space. :man_facepalming:

**Comment by p455w0rd** [comment]
ok..well..that sucks..but I'm not sure what you're wanting me to do about your system being messed up?

**Comment by patrickreader** [comment]
No, the lib still shouldn't spam thousands of times.

**Comment by p455w0rd** [comment]
you're literally the only person in the world this is happening to...

**Comment by p455w0rd** [comment]
and the lib doesn't spam thousands of times on a normal system as I put in checks for timeouts n what not..this is not an issue on my end
