### ISSUE TITLE
still not server side only

### ISSUE THREAD

**Issue by TMFuzz** [p455w0rd/p455w0rds-Library#17]
I can't join the server running p455w0rdslib-1.12-2.0.35.jar  
It is only on the server hosting Sev Tech Ages 3.0.8 minecraft 1.12.2

**Comment by p455w0rd** [comment]
yeah..p455w0rd'sLib isn't server-side only...gg

**Comment by TMFuzz** [comment]
Then your claims that MOTD Customizer being server side only are false. If
it requires libraries that are not server side only making this mod not
server side only.

**Comment by p455w0rd** [comment]
pwlib is only required for 1.7.10..my claims are valid
