### ISSUE TITLE
False advertisement. 

### ISSUE THREAD

**Issue by TMFuzz** [p455w0rd/p455w0rds-Library#18]
For the mod MOTD Customizer you claim.
A Forge Server Side-Only mod to customize your server MOTD!

Requires Libraries that are **NOT** server side only negates the claim that it is server side. 
Granted while CustomMOTD-1.12.2-1.1.6.jar can be on the server only. It won't work without the library which is required to be on the client. 

This is like calling Mac Donald's organic.

**Comment by p455w0rd** [comment]
you do not need p455w0rdslib for 1.12
