### ISSUE TITLE
[1.7.10] Crash on server startup Potential Mod Compatibility Issue

### ISSUE THREAD

**Issue by ryu777mtg** [p455w0rd/p455w0rds-Library#19]
Complete fresh install

Minecraft Version 1.7.10
Forge Version 10.13.4.1614

Mods used
CanIJoinNow 1.7.10 Version 1.0-3
CustomMOTD 1.7.10 Version 1.0.2
p455w0rdslib 1.7.10 Version 1.0.4

[Crash Report Log](https://pastebin.com/ChHYqkNR)
[Lastest.log Log](https://pastebin.com/eRdeWG1v)

Spits out a NoSuchMethodError
Also I can verify the same error happens even without the CanIJoinNow mod so it does happen with only just the two.

I can also verify that p455w0rdslib 1.7.10 Version 1.0.3 gives the same error
However using p455w0rdslib 1.7.10 Version 1.0.2 alleviates the issue and everything loads but am unable to see the info from CanIJoinNow 1.7.10 1.0-3 so I don't know if it's because your mod rewrites over everything but was wondering if there could be a fix to allow both mods to do coexist.

Guess it could be mod compatibility issue as well.

**Comment by p455w0rd** [comment]
1.7.10 is obsolete, I do not support this version.

**Comment by ryu777mtg** [comment]
Well that really sucks to hear but glad you at least even gave it a read through

Thank you for your time.
