### ISSUE TITLE
Lib Server side or client sided?

### ISSUE THREAD

**Issue by rservices** [p455w0rd/p455w0rds-Library#2]
I am wanting to use your MOTD forge mod it does say server side but as for your LIB is that a client side? or a server sided mod? is there a way to use your mod without the LIB if it is client side?

**Comment by p455w0rd** [comment]
i'll look into it

**Comment by rservices** [comment]
Any news on the issue?

**Comment by p455w0rd** [comment]
it's both..no way to use without it..however, I wil consider making this server-side only in the next version.

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/p455w0rds-motd-customizer/files/2484913 - no more p455w0rdslib dep :)
