### ISSUE TITLE
Crash with ProjectE

### ISSUE THREAD

**Issue by Cazadorsniper** [p455w0rd/p455w0rds-Library#21]
p455w0rdslib-1.12.2-2.1.41

Downgrading that allows me to load the pack fine.

https://github.com/sinkillerj/ProjectE/issues/1866

**Comment by GhEppIO82** [comment]
Yes bro !

**Comment by p455w0rd** [comment]
wokrin on it

**Comment by GhEppIO82** [comment]
:)

**Comment by ghost** [comment]
If this was supposed to be fixed in .42 it isn't >.>

**Comment by p455w0rd** [comment]
yup...i removed my coremod...there's literally nothing else I can do, so don't use my stuff with ProjectE i guess

**Comment by ghost** [comment]
No offense meant, but I don't think people are going to accept that as an answer, both ProjectE and mods like WCT and Avaritia are too popular and too commonly used together. That said, I don't think anyone is expecting a quick fix to this.

**Comment by p455w0rd** [comment]
So, Brandon has agreed to work with on getting this fixed and getting /dank/null working..he just went to bed tho..so it'll be at least 8 hrs before we're working on it..but we'll do our best

**Comment by ghost** [comment]
Sounds like a plan.

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/p455w0rds-library/files/2699293 hotfix for now
