### ISSUE TITLE
Error when loading Minecraft

### ISSUE THREAD

**Issue by ghost** [p455w0rd/p455w0rds-Library#22]
Took me a while to find the source of the crash, but with the 4/14 update on the library, I start up minecraft with this error when loading mods.

```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/elytradev/mirage/event/GatherLightsEvent
```

The server runs fine with the update, but the client crashes.
I'm only playing with Applied Energistics 2 and Industrial Craft 2, along with p455w0rd's mods.

Not entirely sure if it's the library, but it does work again when I downgrade to the December update.

Thanks~

**Comment by p455w0rd** [comment]
there were three updates today..please get the latest and confirm this is still happening

**Comment by ghost** [comment]
Twitch cache broke on my machine, I do see the updates now. Sorry!

**Comment by p455w0rd** [comment]
all good :) thank you
