### ISSUE TITLE
Minecraft crashed on world startup

### ISSUE THREAD

**Issue by Andrievs** [p455w0rd/p455w0rds-Library#24]
I had recently started using the FTB Presents Stoneblock 2 with the Twitch starter.
I had generated the world previously and it worked great, but now (a few days later)  the game crashes with this crash report: [Report](https://paste.dimdev.org/pizolugenu.mccrash)

No alteration to the mod pack have been done and no advanced machinery has been built (aka no item pipes, automation devices, chunk loaders, AE, redstone diveces, generators and only the overworld has been generated).

**Comment by p455w0rd** [comment]
should be fixed in latest version, report back if you experience this again
