### ISSUE TITLE
ERROR! Help me!

### ISSUE THREAD

**Issue by RubiksCubei** [p455w0rd/p455w0rds-Library#29]
![image](https://user-images.githubusercontent.com/48173817/59792178-27e64500-9306-11e9-8285-5680ffba3bb4.png)

server：Sponge Forge (spongeforge-1.12.2-2838-7.1.7-RC3777)
Forge：forge-1.12.2-14.23.5.2838-universal

Container was not captured. No ClickInventoryEvent will be fired! Container: class p455w0rd.wct.container.ContainerWCT PacketState: PrimaryInventoryShiftClick

**Comment by p455w0rd** [comment]
I gave it an honest attempt. Unfortunately, Sponge and Forge just don't play well at times. Unless gabizou wishes to give some insight as to what I need to do to fix this, Unfortunately, [this](https://github.com/SpongePowered/SpongeCommon/blob/78b2bbe47f4670d17ac08f2213a9cd1d5473fde5/src/main/java/org/spongepowered/common/event/tracking/phase/packet/inventory/PrimaryInventoryShiftClick.java#L53) is where the trail to figuring out what is doing stops as it references the class `org.spongepowered.api.event.SpongeEventFactory` which when looking for this in the Sponge API's source, as you can see [here](https://github.com/SpongePowered/SpongeAPI/tree/stable-7/src/main/java/org/spongepowered/api/event), this file doesn't exist. Sorry :(
