### ISSUE TITLE
ProjectE dependency is not lowercase

### ISSUE THREAD

**Issue by mezz** [p455w0rd/p455w0rds-Library#3]
https://github.com/p455w0rd/p455w0rds-Library/blob/a058b2e5acce96ece2eb86664c882ed3a2c762c7/src/main/java/p455w0rdslib/LibGlobals.java#L14

Dependencies with uppercase ModIds will do nothing, since all modIds have to be lowercase.

**Comment by p455w0rd** [comment]
thx :)
