### ISSUE TITLE
Game crashes when loading certain blocks (possibly RandomThings related)

### ISSUE THREAD

**Issue by YakoSWG** [p455w0rd/p455w0rds-Library#30]
[crash-2019-06-20_20.37.19-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3311796/crash-2019-06-20_20.37.19-client.txt)

**Comment by YakoSWG** [comment]
Posting this for a friend (Resisbence) who does not have a GitHub account.

**Comment by p455w0rd** [comment]
thank you.looking into it

**Comment by Y0ungSandwich** [comment]
Having a similar issue with with What looks like Random Things.
https://gist.github.com/Y0ungSandwich/baae1437eaacc6127e28235039a42c20

I see your label of being fixed in dev so I expect you've gotten it. Figured I'd leave just in case.

**Comment by the-vindex** [comment]
Duplicate to #32 ? I get the same crash with forestry on top of the stack https://pastebin.com/LAtYDiSr.
