### ISSUE TITLE
World exploration causing massive frame lag

### ISSUE THREAD

**Issue by RedBlockCreator** [p455w0rd/p455w0rds-Library#33]
Using the mod Lag Goggles and loading chunks(be it newly generated or previously generated) I discovered this library was causing a lot of fame skips. It was causing about 5,000,000ns/f of frame lag to be precise. 
To confirm the data i was getting i removed this mod and the problem ceased to exist.

**Comment by p455w0rd** [comment]
Yeah, I was informed of this and fixed it in dev. I'm hoping for pwlib and /dank/null updates tomorrow

**Comment by RedBlockCreator** [comment]
Great to hear. Mind if I ask what was causing it(just out or curiosity)?

**Comment by p455w0rd** [comment]
this implementation i was trying to do for caching raw blocks (actually i was just caching their positions) and relying on an interface implementation of my colored light shader since there are no capabilities for blocks..it was a just a bad idea..I've removed that system now in favor of only supporting tiles

**Comment by ghost** [comment]
I came here to report this same issue; glad to hear it's already been fixed!

Any ETA on when the fixed version will be released?

**Comment by pyure** [comment]
Our team is having the same concern.  Does anyone know what p455w0rd's release cycle is like?  I want to monitor regularly for fix.

**Comment by asiekierka** [comment]
:man_shrugging: 

Sending a fix in about 10 minutes. And it even preserves block support!

**Comment by asiekierka** [comment]
https://github.com/p455w0rd/p455w0rds-Library/pull/43
