### ISSUE TITLE
Dynamic Lighting seems to make blindness function improperly

### ISSUE THREAD

**Issue by TGDesigner** [p455w0rd/p455w0rds-Library#38]
Minecraft Version 1.12.2
Forge Version: 14.23.5.2838
Mod Version: 1.12.2-2.2.151

When the dynamic light setting is on, the blindness potion effect only darkens the sky, but still allows normal vision otherwise.

**Comment by mxnmnm** [comment]
Yep I can confirm

**Comment by ElvenChaos** [comment]
Some additional details to this bug I came across:

In the config, toggling "EnableShaders" to "false" fixes the issue.
The issue doesn't just affect blindness; it seems to break vanilla minecraft's fog entirely:

1. Render distance fog will not render
2. Blindness, which renders said fog close to player, can't render the fog. Entities are still dyed to the color of the fog (black).
3. Thaumcraft warp effect that spawns eldritch guardians and renders the fog close to player can't render the fog. Entities are still dyed the natural light blue fog color.

**Comment by p455w0rd** [comment]
should be resolved since I removed shaders
