### ISSUE TITLE
p455w0rd library keeps crashing po3 when loading up the modpack on twitch launcher

### ISSUE THREAD

**Issue by deathskater21** [p455w0rd/p455w0rds-Library#41]
[crash-2019-07-08_11.18.49-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3372317/crash-2019-07-08_11.18.49-client.txt)

**Comment by Summpot** [comment]
The same issue occured on my computer and it can be solved by switching OpenGL rendering GPUs from automatic selection to your discrete graphics card at NVIDIA Control Panel.

**Comment by runescapejon** [comment]
Duplication of https://github.com/p455w0rd/p455w0rds-Library/issues/31
