### ISSUE TITLE
Upgrade p455w0rdslib-1.12.2-2.2.156 causes dank null to crash game while loading

### ISSUE THREAD

**Issue by wideblaze** [p455w0rd/p455w0rds-Library#44]
https://paste.dimdev.org/gapitilomu.mccrash

I'm guessing that there is a companion dank/null update that was not available on curse at the time of updating lib mod.

I'll just back rev until cleared

**Comment by GhEppIO82** [comment]
yes, I think so, but every update and so

**Comment by NordicGamerFE** [comment]
Heres the crash log in an enviorment with only the mods that cause the issue
https://pastebin.com/fHDMGKTu
Here is the debug log
https://pastebin.com/xtUeZwi3
And here is the startup log
https://pastebin.com/BHnsQbUa

**Comment by GhEppIO82** [comment]
fix bro ?!?

**Comment by p455w0rd** [comment]
here you go:
[the permanent fix](https://www.curseforge.com/minecraft/mc-mods/dank-null)
enjoy :)

**Comment by GhEppIO82** [comment]
what ??? where is the fix dude ???

**Comment by p455w0rd** [comment]
1: This issue is with /dank/null and this tracker is for p455w0rd's Library.
2: Due to many peoples' impatience, selfishness, demanding attitudes, and derogatory messages, I have discontinued /dank/null until I can regain the mental sanity I need to work on it. The fix is that there is no more /dank/null. Remove it from your packs and have a nice life :)

**Comment by GhEppIO82** [comment]
then don't release updates if you don't want people to blast you

**Comment by Samrock14** [comment]
This is the issue. People bugging a mod dev on ANOTHER one of their mods for an update. If i was pa55w0rd i wouldve done the same thing and remove any available jar files for the mod. People have lives, they dont exist only to update one single mod that a few people complain about. Deal with the mod being gone .you GhEpplO82 are part of the issue with mod developers recieving hate for being busy.

**Comment by 43eyes** [comment]
Use the most recent version of /dank/null and use THIS version of the library:
https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/download/2726877

Fixed it for me

**Comment by NordicGamerFE** [comment]
the behavior of GhEppIO82 is of someone who never has never touched java in any meaningful way, and lets not talk about the disrespect maybe watching a little to much drdisrespect?

**Comment by marka65** [comment]
@GhEppIO82 - why don't you get off your lazy arse and learn some java and be productive - maybe get out of your mums basement once in a while.

**Comment by p455w0rd** [comment]
ty to those that helped others with a temp solution during all this...you guys are the real superstars here <3
