### ISSUE TITLE
Crash when Launching FTB Interactions

### ISSUE THREAD

**Issue by joshp1445** [p455w0rd/p455w0rds-Library#46]
Hello,
I'm trying to launch FTB Interactions from an older computer. Loading goes fine until stage 2/7 and loading P455w0rd's Library, at which point it crashes for an unknown reason. I am unable to open the crash report as well. Is there anything someone on this forum knows that might help me get past this point? Thanks!

**Comment by phadac** [comment]
İ just getting same problem on stoneblock 2,btw i can play sb2 before this updates

**Comment by karagozk** [comment]
I am getting the same problem in stoneblock2 1.15
