### ISSUE TITLE
[1.12.2] - p455w0rds-Library, Crashing Java

### ISSUE THREAD

**Issue by wolfkidsounds** [p455w0rd/p455w0rds-Library#49]
Hey,
I've the following problem using the "DigSite" Modpack. The pack crashed and I tried to isolate the mod causing the problem. I've found that the p455w0rds library creates the crash which is required for the mod /dank/null.
The crash only occurs on versions "2.2.132" and later. I've also tried the newest version: "2.2.156" which results in the same crash.
The crash only happens on systems with intel graphic 3000 and lower.
Java Version: Version 8 Update 221
Forge Version: forge-1.12.2-14.23.5.2844

I've attached the java error log.
[hs_err_pid6100.log](https://github.com/p455w0rd/p455w0rds-Library/files/3555634/hs_err_pid6100.log)

As well as the minecraft log:
[latest.log](https://github.com/p455w0rd/p455w0rds-Library/files/3555637/latest.log)

In addition I tried to disable all config option with no effect on this crash.

I hope you can fix this or help me out to fix this.

Thanks for all the nice mods so far <3

**Comment by p455w0rd** [comment]
If you would like to test a dev version, please add me on discord `TheRealp455w0rd#7817`

**Comment by p455w0rd** [comment]
should be resolved since I removed shaders
