### ISSUE TITLE
Config option to disable holiday wings?

### ISSUE THREAD

**Issue by zerotheliger** [p455w0rd/p455w0rds-Library#5]
i noticed that the mod itself was generating wings would it be possible for a config option to disable these?

**Comment by Dragnier** [comment]
There already is one. In the config for p455w0rd's Library, set B:EnableContributorCosmetics=false
and you won't have the wings anymore.

**Comment by zerotheliger** [comment]
oh if that does work then sweet cause apparently it was disabling peoples minecon capes and donor capes.
