### ISSUE TITLE
Interoperability Issue with Better Portals

### ISSUE THREAD

**Issue by dequbed** [p455w0rd/p455w0rds-Library#54]
When `B:EnableShaders=true` is set you will get the following graphical artifacts for better portals:

![2019-11-14_16 32 12](https://user-images.githubusercontent.com/3063480/68871738-3130dd80-06fd-11ea-91c4-3893142792ce.png)
![2019-11-14_16 30 39](https://user-images.githubusercontent.com/3063480/68871748-33933780-06fd-11ea-99f2-10718f74b274.png)

Screenshots were taken on Minecraft version 1.12.2 with
- Forge 1.12.2-14.23.5.2838
- p455w0rdslib-1.12.2-2.2.156.jar (md5sum 56a57b60eff38f98cf0228b802df2322)
- betterportals-0.3.7.1.jar (md5sum d11bf3d057509a11b8738df604094d46)

The issue does *not* appear when `EnableShaders` is set to `false`.

Related issue in the Better Portals repository: Johni0702/BetterPortals#410

**Comment by p455w0rd** [comment]
I'll be removing the shaders stuff from pwlib. Thanks for the report :)

**Comment by p455w0rd** [comment]
should be resolved since I removed shaders
