### ISSUE TITLE
ExceptionAccessViolation crashing to desktop

### ISSUE THREAD

**Issue by onesingleerror** [p455w0rd/p455w0rds-Library#55]
I've been trying to fix this issue on my own forever, but it didn't get me anywhere. 

specs: https://pastebin.com/UTsCpEME

java crash report: https://pastebin.com/qaQAdEtY

minecraft crash report: https://pastebin.com/ypAPKC4H

sorry if this isn't helpful, this is my first time using github.

**Comment by p455w0rd** [comment]
should be resolved since I removed shaders
