### ISSUE TITLE
Crash with latest version and aroma core

### ISSUE THREAD

**Issue by mxnmnm** [p455w0rd/p455w0rds-Library#56]
https://pastebin.com/vxCAhRz0

**Comment by BedrockLegends** [comment]
[crash-2019-11-19_19.00.44-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3866766/crash-2019-11-19_19.00.44-client.txt)

**Comment by p455w0rd** [comment]
forgot to upload [ae2wtlib update](https://www.curseforge.com/minecraft/mc-mods/ae2wtlib/files/2829802)..my bad..
