### ISSUE TITLE
Crash with Arcane Archives and AE2Stuff

### ISSUE THREAD

**Issue by Archilyte** [p455w0rd/p455w0rds-Library#57]
https://paste.dimdev.org/goyibewaco.mccrash

the latest version of p455w0rds-Library as of this writing crashes with the latest version of arcane archives that can be retrieved from curseforge as of this writing, along with the latest version of AE2Stuff as of this writing. Latest forge as of this writing.

**Comment by Archilyte** [comment]
seems to be the same as [this](https://github.com/p455w0rd/p455w0rds-Library/issues/56) but im not sure

**Comment by p455w0rd** [comment]
fixed [in this update](https://www.curseforge.com/minecraft/mc-mods/ae2wtlib/files/2829802)
