### ISSUE TITLE
[1.12.2-2.3.159] Crash with java.lang.NoSuchMethodError: p455w0rdslib.proxy.CommonProxy.areShadersEnabled

### ISSUE THREAD

**Issue by Meryl** [p455w0rd/p455w0rds-Library#58]
Using the newest dank null (1.12.2-1.7.84) and p455w0rdslib (1.12.2-2.3.159) I get a crash on startup of my server (a slightly customized FTB Revelation 3.2.1), with the following error message:

>  java.lang.NoSuchMethodError: p455w0rdslib.proxy.CommonProxy.areShadersEnabled

I think that's the relevant bit, the full crash log is available [here](https://pastebin.com/uQZyeTRr). This is in a world that previously used dank null 1.6.80 (and 2.2.156 for p455wordslib).

*edit:* screwed up the previous version numbers, fixed now

**Comment by p455w0rd** [comment]
update to absolute latest (check CF site..not Twitch Desktop as I have had reports of Twitch Desktop downloading outdated versions)
