### ISSUE TITLE
p455w0rdslib.proxy.CommonProxy.areShadersEnabled()Z

### ISSUE THREAD

**Issue by AiMLESS2k** [p455w0rd/p455w0rds-Library#59]
I saw that somebody got the same error as me, but i'm using the latest version from CF (p455w0rdslib-1.12.2-2.3.161).

Here is the crash-report: https://pastebin.com/DY8X1ywy

**Comment by p455w0rd** [comment]
the error is with ae2wtlib which is outdated, please update ae2wtlib to 1.0.34
