### ISSUE TITLE
Mention on the CurseForge page that this mod adds colored dynamic lighting

### ISSUE THREAD

**Issue by aaronhowser1** [p455w0rd/p455w0rds-Library#60]
Like #36 says, it's not easy to find out that this is the mod that adds colored lighting. It's disabled by default now, but some people might *want* colored dynamic lighting and not know it's an option, and enable it in the config.

Alternatively, make it a different mod. Colored dynamic lighting is a feature, not a part of a codebase.

**Comment by p455w0rd** [comment]
shaders have been completely removed
