### ISSUE TITLE
Crash when using creative menu

### ISSUE THREAD

**Issue by Kehaan** [p455w0rd/p455w0rds-Library#63]
Hello

I am getting a crash when using one of the pages in the creative menu. It seems that it is this mod that causes the issue. This is for 1.12.2

Crashlog:

[crash-2020-01-01_16.50.31-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/4014222/crash-2020-01-01_16.50.31-client.txt)

**Comment by cjm721** [comment]
Crash is from the Wireless crafting terminal library ie https://github.com/p455w0rd/AE2WirelessTerminalLibrary
