### ISSUE TITLE
Having an issue when running All The Mods 3 Lite

### ISSUE THREAD

**Issue by z6kku** [p455w0rd/p455w0rds-Library#64]
![Crash](https://user-images.githubusercontent.com/59539691/71784802-9b5f5380-2fc5-11ea-8e9e-390d798735af.PNG)

Having this issue

**Comment by Twisted-Code** [comment]
Does ATM3L (that pack) happen to have Railcraft? I got a similar top-level exception to the one shown there (by the way, you should REALLY include the full crash report, or at the very least the full stacktrace. I doubt p455w0rd will be able to help without more information like the crash report and/or debug.log), except it was thrown by Railcraft and referenced p455w0rd's Lib, not thrown by p455w0rd's Lib directly. Still, I'll make sure to reference this when I open an issue...

**Comment by cjm721** [comment]
Need the full log to be able to debug anything. Please open new bug with the full log.
