### ISSUE TITLE
Crash on load - Seems to be clashing with immersive Engineering

### ISSUE THREAD

**Issue by willcaddy** [p455w0rd/p455w0rds-Library#67]
When the game loads, it crashes when it goes through the pre-initialisation stage when it gets to the immersive engineering mod. I saw in the crash report that it seemed to be a conflict between the Immersive Engineering mod and the p455w0rds-Library. 

Here is the crash report: https://pastebin.com/u06xTjFv
 
I am trying to use the latest version of Dank/Null but I cant because of the issue. 

Let me know if you need any more info :) and Thanks :)

**Comment by cjm721** [comment]
This is an issue for https://github.com/p455w0rd/AE2WirelessTerminalLibrary. The mod is https://www.curseforge.com/minecraft/mc-mods/ae2wtlib
