### ISSUE TITLE
crash when entering world

### ISSUE THREAD

**Issue by Trixz2018** [p455w0rd/p455w0rds-Library#7]
https://pastebin.com/iL3e7Ldx

I don't why it crashed, the only thing i have done is updated the thermal mods and then this happened.
i was able to enter my world after relaunch without it crashing so im clueless on why it happened in the first place

**Comment by p455w0rd** [comment]
I can see how this could happen...probably pretty rare, but I'll get a new version up soon..thanks for reporting :)

**Comment by Trixz2018** [comment]
np, glad to be of assistance

**Comment by Kiyaku** [comment]
Just had the same (i think) crash happening with the latest version: https://pastebin.com/ebFxfRXy

I added Embers + Soots but also updated a couple mods. Will try to see what may conflict.

**Comment by Trixz2018** [comment]
hmm that is weird, he had fixed it in the last build he released on curse
