### ISSUE TITLE
Crash - Industrial Forgoing, Forestry, P455w0rd lib listed in trace.

### ISSUE THREAD

**Issue by ProsperCraft** [p455w0rd/p455w0rds-Library#9]
https://github.com/ForestryMC/ForestryMC/issues/1984

**Comment by p455w0rd** [comment]
Some mod is referencing a client-side only class on server side. Fortunately, it's not me. I also doubt it's Forestry. It could actually be a mod not even mentioned in the report. I've never dealt with Industrial Foregoing so it's possible that it's on their end.
